version: '3.7'
services:
  product-service:
    image: product-service:v1
    ports:
      - "8002:8002"
    restart: always
    networks:
      - springcloud
  item-service:
    image: basket-service:v1
    ports:
      - "8001:8001"
    restart: always
    networks:
      - springcloud
    depends_on:
      - product-service
networks:
  springcloud: